package com.mycompany.ediciondecodigo;

import java.awt.Color;
import java.io.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FormularioAgregar extends javax.swing.JFrame {
    
    /**
     * Creates new form FormularioAgregar
     */
    public FormularioAgregar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        LabelLugar = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JButton();
        BotonGuardar = new javax.swing.JButton();
        EquipoVisitantejLabel = new javax.swing.JLabel();
        EquipoVisitantejLabel1 = new javax.swing.JLabel();
        NombreEquipoTextField = new javax.swing.JTextField();
        EntrenadorTextField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setPreferredSize(new java.awt.Dimension(500, 350));
        MainPanel.setRequestFocusEnabled(false);
        MainPanel.setVerifyInputWhenFocusTarget(false);
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelLugar.setBackground(new java.awt.Color(255, 255, 255));
        LabelLugar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        LabelLugar.setForeground(new java.awt.Color(0, 0, 0));
        LabelLugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelLugar.setText("FORMULARIO PARA AGREGAR");
        MainPanel.add(LabelLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 300, 40));

        BotonRegresar.setBackground(new java.awt.Color(0, 102, 0));
        BotonRegresar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonRegresar.setForeground(new java.awt.Color(0, 0, 0));
        BotonRegresar.setText("REGRESAR");
        BotonRegresar.setBorder(null);
        BotonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseExited(evt);
            }
        });
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });
        MainPanel.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 150, 40));

        BotonGuardar.setBackground(new java.awt.Color(0, 102, 0));
        BotonGuardar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        BotonGuardar.setText("GUARDAR");
        BotonGuardar.setBorder(null);
        BotonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });
        MainPanel.add(BotonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 150, 40));

        EquipoVisitantejLabel.setBackground(new java.awt.Color(255, 255, 255));
        EquipoVisitantejLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        EquipoVisitantejLabel.setForeground(new java.awt.Color(0, 0, 0));
        EquipoVisitantejLabel.setText("Nombre del entrenador: ");
        MainPanel.add(EquipoVisitantejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 150, 30));

        EquipoVisitantejLabel1.setBackground(new java.awt.Color(255, 255, 255));
        EquipoVisitantejLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        EquipoVisitantejLabel1.setForeground(new java.awt.Color(0, 0, 0));
        EquipoVisitantejLabel1.setText("Nombre del equipo: ");
        MainPanel.add(EquipoVisitantejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 130, 30));

        NombreEquipoTextField.setBackground(new java.awt.Color(255, 255, 255));
        NombreEquipoTextField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        NombreEquipoTextField.setForeground(new java.awt.Color(0, 0, 0));
        NombreEquipoTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NombreEquipoTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        MainPanel.add(NombreEquipoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 200, 30));

        EntrenadorTextField.setBackground(new java.awt.Color(255, 255, 255));
        EntrenadorTextField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        EntrenadorTextField.setForeground(new java.awt.Color(0, 0, 0));
        EntrenadorTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainPanel.add(EntrenadorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 200, 30));

        idLabel.setBackground(new java.awt.Color(255, 255, 255));
        idLabel.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(0, 0, 0));
        idLabel.setText("id:");
        MainPanel.add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 30));

        idTextField.setBackground(new java.awt.Color(255, 255, 255));
        idTextField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        idTextField.setForeground(new java.awt.Color(0, 0, 0));
        idTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        idTextField.setToolTipText("");
        idTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        idTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        MainPanel.add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseEntered
        // TODO add your handling code here:
        BotonRegresar.setBackground(new Color(51, 255, 51));
    }//GEN-LAST:event_BotonRegresarMouseEntered

    private void BotonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseExited
        // TODO add your handling code here:
        BotonRegresar.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_BotonRegresarMouseExited

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        // TODO add your handling code here:
        GestionEquipos boton_regresar = new GestionEquipos();
        boton_regresar.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        // TODO add your handling code here:
        
        File Archivo = new File("equipos.txt");
        try{
            if(!Archivo.exists()){
                Archivo.createNewFile();
            }
            if(" ".equals(idTextField.getText()) || " ".equals(NombreEquipoTextField.getText()) || " ".equals(EntrenadorTextField.getText())){
                JOptionPane.showMessageDialog(null,"Error, no se pueden ingresar espacios en blanco");
            }
            else if(idTextField.getText().isEmpty() || NombreEquipoTextField.getText().isEmpty() || EntrenadorTextField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Error, hay casillas vacias");
            }
            else{
                try (FileWriter escribir_fw = new FileWriter(Archivo, true); BufferedWriter transferir_bw = new BufferedWriter(escribir_fw); PrintWriter imprimir_pw = new PrintWriter(transferir_bw)) {
                
                String equipo_id = String.valueOf(idTextField.getText());
                String agregar_fila = equipo_id+";"+NombreEquipoTextField.getText()+";"+EntrenadorTextField.getText()+";";
                
                if(!"".equals(agregar_fila)){
                    imprimir_pw.append(agregar_fila);
                    transferir_bw.newLine();
                    JOptionPane.showMessageDialog(null, "Datos guardados correctamente");
                    Menu regresar_menu = new Menu();
                    regresar_menu.setVisible(true);
                    dispose();
                }
                    
                } catch (IOException ex) {
                    Logger.getLogger(FormularioAgregar.class.getName()).log(Level.SEVERE, null, ex);
                }
              
                }
                
                }
                catch (IOException e) {
                    System.out.println("Error");
                }  
        
            
                    
        
 
    }//GEN-LAST:event_BotonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JTextField EntrenadorTextField;
    private javax.swing.JLabel EquipoVisitantejLabel;
    private javax.swing.JLabel EquipoVisitantejLabel1;
    private javax.swing.JLabel LabelLugar;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextField NombreEquipoTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    // End of variables declaration//GEN-END:variables
}
