package com.mycompany.ediciondecodigo;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class GestionEquipos extends javax.swing.JFrame {
    int xMouse, yMouse;

    public GestionEquipos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GestionEquipoTittle = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        ExitButton = new javax.swing.JButton();
        BotonListarEquipos = new javax.swing.JButton();
        BotonAgregarEquipo = new javax.swing.JButton();
        BotonModificarEquipo = new javax.swing.JButton();
        BotonBorrarEquipo = new javax.swing.JButton();
        TextoLugar = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JButton();
        TextoGUI = new javax.swing.JLabel();

        GestionEquipoTittle.setBackground(new java.awt.Color(255, 255, 255));
        GestionEquipoTittle.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        GestionEquipoTittle.setForeground(new java.awt.Color(0, 0, 0));
        GestionEquipoTittle.setText("Gestión de Equipo");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setMinimumSize(new java.awt.Dimension(800, 500));
        MainPanel.setPreferredSize(new java.awt.Dimension(400, 600));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderPanel.setBackground(new java.awt.Color(255, 255, 255));
        HeaderPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderPanelMouseDragged(evt);
            }
        });
        HeaderPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderPanelMousePressed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(255, 255, 255));
        ExitButton.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(51, 51, 51));
        ExitButton.setText("X");
        ExitButton.setBorder(null);
        ExitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 400, Short.MAX_VALUE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MainPanel.add(HeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 50));

        BotonListarEquipos.setBackground(new java.awt.Color(0, 102, 0));
        BotonListarEquipos.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonListarEquipos.setForeground(new java.awt.Color(0, 0, 0));
        BotonListarEquipos.setText("Listar equipos registrados");
        BotonListarEquipos.setBorder(null);
        BotonListarEquipos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonListarEquipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonListarEquiposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonListarEquiposMouseExited(evt);
            }
        });
        BotonListarEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListarEquiposActionPerformed(evt);
            }
        });
        MainPanel.add(BotonListarEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 250, 50));

        BotonAgregarEquipo.setBackground(new java.awt.Color(0, 102, 0));
        BotonAgregarEquipo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonAgregarEquipo.setForeground(new java.awt.Color(0, 0, 0));
        BotonAgregarEquipo.setText("Formulario para agregar ");
        BotonAgregarEquipo.setBorder(null);
        BotonAgregarEquipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAgregarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonAgregarEquipoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonAgregarEquipoMouseExited(evt);
            }
        });
        BotonAgregarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarEquipoActionPerformed(evt);
            }
        });
        MainPanel.add(BotonAgregarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 250, 50));

        BotonModificarEquipo.setBackground(new java.awt.Color(0, 102, 0));
        BotonModificarEquipo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonModificarEquipo.setForeground(new java.awt.Color(0, 0, 0));
        BotonModificarEquipo.setText("Formulario para modificar");
        BotonModificarEquipo.setBorder(null);
        BotonModificarEquipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonModificarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonModificarEquipoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonModificarEquipoMouseExited(evt);
            }
        });
        BotonModificarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarEquipoActionPerformed(evt);
            }
        });
        MainPanel.add(BotonModificarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 250, 50));

        BotonBorrarEquipo.setBackground(new java.awt.Color(0, 102, 0));
        BotonBorrarEquipo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonBorrarEquipo.setForeground(new java.awt.Color(0, 0, 0));
        BotonBorrarEquipo.setText("Formulario para eliminar");
        BotonBorrarEquipo.setBorder(null);
        BotonBorrarEquipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonBorrarEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonBorrarEquipoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonBorrarEquipoMouseExited(evt);
            }
        });
        BotonBorrarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarEquipoActionPerformed(evt);
            }
        });
        MainPanel.add(BotonBorrarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 250, 50));

        TextoLugar.setBackground(new java.awt.Color(255, 255, 255));
        TextoLugar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        TextoLugar.setForeground(new java.awt.Color(0, 0, 0));
        TextoLugar.setText("GESTIÓN DE EQUIPOS");
        MainPanel.add(TextoLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 250, 50));

        BotonRegresar.setBackground(new java.awt.Color(0, 102, 0));
        BotonRegresar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        BotonRegresar.setForeground(new java.awt.Color(0, 0, 0));
        BotonRegresar.setText("REGRESAR");
        BotonRegresar.setBorder(null);
        BotonRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseExited(evt);
            }
        });
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });
        MainPanel.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 130, 40));

        TextoGUI.setBackground(new java.awt.Color(255, 255, 255));
        TextoGUI.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        TextoGUI.setForeground(new java.awt.Color(0, 0, 0));
        TextoGUI.setText("UPC AGUACHICA FUTSALA");
        MainPanel.add(TextoGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 300, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPanelMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeaderPanelMouseDragged

    private void HeaderPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderPanelMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderPanelMousePressed

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void ExitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseEntered
        // TODO add your handling code here:
        ExitButton.setBackground(Color.red);
        ExitButton.setForeground(Color.white);
    }//GEN-LAST:event_ExitButtonMouseEntered

    private void ExitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseExited
        // TODO add your handling code here:
        ExitButton.setBackground(Color.white);
        ExitButton.setForeground(Color.black);
    }//GEN-LAST:event_ExitButtonMouseExited

    private void BotonListarEquiposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonListarEquiposMouseEntered
        // TODO add your handling code here:
        BotonListarEquipos.setBackground(new Color(51, 255, 51));
    }//GEN-LAST:event_BotonListarEquiposMouseEntered

    private void BotonListarEquiposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonListarEquiposMouseExited
        // TODO add your handling code here:
        BotonListarEquipos.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_BotonListarEquiposMouseExited

    private void BotonAgregarEquipoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarEquipoMouseEntered
        // TODO add your handling code here:
        BotonAgregarEquipo.setBackground(new Color(51, 255, 51));
    }//GEN-LAST:event_BotonAgregarEquipoMouseEntered

    private void BotonAgregarEquipoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarEquipoMouseExited
        // TODO add your handling code here:
        BotonAgregarEquipo.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_BotonAgregarEquipoMouseExited

    private void BotonModificarEquipoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonModificarEquipoMouseEntered
        // TODO add your handling code here:
        BotonModificarEquipo.setBackground(new Color(51, 255, 51));
    }//GEN-LAST:event_BotonModificarEquipoMouseEntered

    private void BotonModificarEquipoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonModificarEquipoMouseExited
        // TODO add your handling code here:
        BotonModificarEquipo.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_BotonModificarEquipoMouseExited

    private void BotonBorrarEquipoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBorrarEquipoMouseEntered
        // TODO add your handling code here:
        BotonBorrarEquipo.setBackground(new Color(51, 255, 51));
    }//GEN-LAST:event_BotonBorrarEquipoMouseEntered

    private void BotonBorrarEquipoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBorrarEquipoMouseExited
        // TODO add your handling code here:
        BotonBorrarEquipo.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_BotonBorrarEquipoMouseExited

    private void BotonListarEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListarEquiposActionPerformed
        // TODO add your handling code here:
        ListarEquipos lista = new ListarEquipos();
        lista.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonListarEquiposActionPerformed

    private void BotonAgregarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarEquipoActionPerformed
        // TODO add your handling code here:
        
        FormularioAgregar agregar_equipo = new FormularioAgregar();
        agregar_equipo.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonAgregarEquipoActionPerformed

    private void BotonRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseEntered
        // TODO add your handling code here:
        BotonRegresar.setBackground(new Color(51, 255, 51));
    }//GEN-LAST:event_BotonRegresarMouseEntered

    private void BotonRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseExited
        // TODO add your handling code here:
        BotonRegresar.setBackground(new Color(0, 102, 0));
    }//GEN-LAST:event_BotonRegresarMouseExited

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        // TODO add your handling code here:
        Menu regresar_menu = new Menu();
        regresar_menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void BotonModificarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarEquipoActionPerformed
        // TODO add your handling code here:
        FormularioModificar modificar_equipo = new FormularioModificar();
        modificar_equipo.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonModificarEquipoActionPerformed

    private void BotonBorrarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarEquipoActionPerformed
        // TODO add your handling code here:
        FormularioEliminar eliminar_equipo = new FormularioEliminar();
        eliminar_equipo.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonBorrarEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GestionEquipos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarEquipo;
    private javax.swing.JButton BotonBorrarEquipo;
    private javax.swing.JButton BotonListarEquipos;
    private javax.swing.JButton BotonModificarEquipo;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel GestionEquipoTittle;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel TextoGUI;
    private javax.swing.JLabel TextoLugar;
    // End of variables declaration//GEN-END:variables
}
